"use strict";
var Profession = type__message.Profession;
var Side = type__piece.Side;
var Color = type__message.Color;
var toPath = type__piece.toPath;
var toPath_ = type__piece.toPath_;
var toUpOrDown = type__piece.toUpOrDown;
var AbsoluteColumn = type__message.AbsoluteColumn;
var AbsoluteRow = type__message.AbsoluteRow;
var calculateMovablePositions = calculate_movable.calculateMovablePositions;
var coordEq = type__piece.coordEq;
var rotateCoord = type__piece.rotateCoord;
var rotateBoard = type__piece.rotateBoard;
var eightNeighborhood = calculate_movable.eightNeighborhood;
var isTamHue = calculate_movable.isTamHue;
var canGetOccupiedBy = calculate_movable.canGetOccupiedBy;
